config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'users#home'

  resources :users, only: [] do
    resources :color_schemes
    resources :favorites, only: [:index, :update]
  end

  resources :color_schemes, only: [:index]
  resources :colors, only: [:create]

  get '/random' => 'color_schemes#random'
  get '/popular' => 'color_schemes#popular'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/auth/github/callback' => 'sessions#create_with_github'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/color.rb
class Color < ApplicationRecord
  has_many :color_scheme_colors
  has_many :color_schemes, through: :color_scheme_colors
end

app/models/color_scheme.rb
class ColorScheme < ApplicationRecord
  belongs_to :user
  has_many :favorite_color_schemes, dependent: :destroy
  has_many :favorited_by, through: :favorite_color_schemes, source: :user
  has_many :color_scheme_colors, dependent: :destroy
  has_many :colors, through: :color_scheme_colors
  validates :name, presence: :true
  accepts_nested_attributes_for :color_scheme_colors

  def self.user_schemes_json(user)
    user_color_schemes_json = {
      id: user.id,
      color_schemes: [],
      }
    user.color_schemes.each_with_index do |cs, i|
      user_color_schemes_json[:color_schemes] <<
        {
          id: "#{cs.id}",
          name: "#{cs.name}",
          user_id: "#{cs.user_id}",
          favorite: user.favorites.include?(cs),
          colors: []
        }
      cs.colors.each do |c|
        user_color_schemes_json[:color_schemes][i][:colors] <<
        {
          id: "#{c.id}",
          hex_code: "#{c.hex_code}",
          color_note: "#{c.color_scheme_colors.first.color_note}"
        }
      end
    end
    user_color_schemes_json
  end

end

app/models/color_scheme_color.rb
class ColorSchemeColor < ApplicationRecord
  belongs_to :color_scheme
  belongs_to :color

  def color_attributes=(color_attributes)
    color_attributes.each do |i, hex_code|
        self.color = Color.new(hex_code: hex_code)
    end
  end

end

app/models/favorite_color_scheme.rb
class FavoriteColorScheme < ApplicationRecord
  belongs_to :user
  belongs_to :color_scheme

  def self.most_popular
    fav_schemes = self.group('color_scheme_id').order('color_scheme_id asc').limit(20)
    fav_schemes.map do |fs|
      ColorScheme.find_by(id: fs.color_scheme_id)
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :color_schemes
  has_many :favorite_color_schemes
  has_many :favorites, through: :favorite_color_schemes, source: :color_scheme

  has_secure_password

  validates :email, presence: true
  validates :email, uniqueness: true
  validates_format_of :email, with: /@/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to login_path unless current_user
  end

  def find_color_scheme
    @color_scheme = ColorScheme.find(params[:id])
  end

  def find_user_id
    @user = User.find(params[:user_id])
  end

end

app/controllers/color_schemes_controller.rb
class ColorSchemesController < ApplicationController
  before_action :authorize
  before_action :find_color_scheme, only: [:edit, :update, :destroy]
  before_action :find_user_id, only: [:new, :edit]

  def index
    if params[:user_id]
      @user = User.find(params[:user_id])
      @color_schemes = @user.color_schemes
      respond_to do |format|
        format.html { render :index }
        format.json { render json: ColorScheme.user_schemes_json(@user) }
      end
    else
      @color_schemes = ColorScheme.all
    end
  end

  def new
    if @user.id == current_user.id
      @color_scheme = ColorScheme.new
      5.times do
        @color_scheme.color_scheme_colors.new.build_color
      end
    else
      flash[:error] = "You cannot create color schemes for others"
      redirect_to new_user_color_scheme_path(current_user)
    end
  end

  def create
    @color_scheme = current_user.color_schemes.new(color_scheme_params)
    if @color_scheme.save
      flash[:success] = "New color scheme created!"
      respond_to do |format|
        format.html { redirect_to user_color_schemes_path }
        format.json { render json: ColorScheme.user_schemes_json(current_user) }
      end
    else
      flash[:error] = @color_scheme.errors.full_messages.to_sentence
      redirect_to new_user_color_scheme_path
    end
  end

  def edit
    if current_user != @user
      flash[:error] = "Not your color scheme"
      redirect_to color_schemes_path
    end
  end

  def update
    if @color_scheme.update(color_scheme_params)
      flash[:success] = "Color scheme updated!"
      redirect_to user_color_schemes_path
    else
      flash[:error] = "Something went wrong"
      render 'edit'
    end
  end

  def destroy
    if current_user.color_schemes.include?(@color_scheme)
      @color_scheme.destroy
      flash[:success] = "Color scheme deleted!"
      redirect_to user_color_schemes_path
    else
      flash[:error] = "Not your color scheme"
      redirect_to user_color_schemes_path
    end
  end

  def popular
    @popular_color_schemes = FavoriteColorScheme.most_popular
  end

  def random
    color_scheme_ids = ColorScheme.ids
    random_id = color_scheme_ids.sample
    @random_scheme =  ColorScheme.find(random_id)
    partial = render_to_string partial: 'color_schemes/random', locals: { random_scheme: @random_scheme }
    respond_to do |format|
      format.html { render :random }
      format.json { render json: {random_partial: partial} }
    end
    # @random_scheme = ColorScheme.offset(rand(ColorScheme.count)).first
  end

  private

  def color_scheme_params
    params.require(:color_scheme).permit(:name, color_scheme_colors_attributes: [:id, :color_note, color_attributes: [:id, :hex_code]])
  end

end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController

  def create
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authorize
  before_action :find_color_scheme, only: [:update]
  before_action :find_user_id, only: [:index]

  def index
    @favorites = @user.favorites
  end

  def show
  end

  def update
    @color_scheme = ColorScheme.find(params[:id])
    type = params[:type]
    if type == "favorite"
      current_user.favorites << @color_scheme
      flash[:success] = "Favorited!"
      redirect_back(fallback_location: user_favorites_path)
    elsif type == "unfavorite"
      current_user.favorites.delete(@color_scheme)
      flash[:success] = "Unfavorited!"
      redirect_back(fallback_location: user_favorites_path)
    else
      flash[:error] = "Something went wrong"
      redirect_back(fallback_location: user_favorites_path)
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    if current_user
      redirect_to root_path
      flash[:error] = "Please log out first"
    end
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:loginerror] = "Invalid Email or Password"
      render :new
    end
  end

  def create_with_github
    user = User.find_or_create_by(uid: auth['uid']) do |u|
      u.email = auth['info']['email']
      u.password = u.password_confirmation = SecureRandom.urlsafe_base64(n=6)
    end
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to login_path
  end

  private

  def auth
    request.env['omniauth.auth']
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, only: :home

  def new
    if current_user
      redirect_to root_path
      flash[:error] = "Please log out first"
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:loginerror] = @user.errors.full_messages.to_sentence
      render :new
    end
  end

  def home
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/color_schemes/_form.html.erb
<%= form_for([@user, @color_scheme]) do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name, class: "u-full-width", placeholder: "Scheme Name"%>
  </p>

  <%= f.label :colors, "Select Colors" %>

  <div class="row">
    <div class="twelve columns">
      <div class="cs-form-container">
        <%= f.label :color_scheme_colors, "Color Notes (optional)", class: "color-note-label" %>
        <%= f.fields_for :color_scheme_colors do |csc| %>
          <%= csc.text_field :color_note, class: "width-20p-notes" %>

          <%= csc.fields_for :color do |c| %>
            <%= c.text_field :hex_code, class: "width-20p-colors tall-input" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

    <p>
      <%= f.submit id: 'newcolorschemesubmit', data: { url: "/users/#{@user.id}/color_schemes" } %>
    </p>
<% end %>

app/views/color_schemes/_index.html.erb
<% if color_schemes.empty? %>
  <p> No color schemes yet! </p>
  <span class="fa fa-plus" aria-hidden="true"></span> <%= link_to "Create one!", new_user_color_scheme_path(current_user) %>
<% else %>
  <% color_schemes.each do |cs| %>
    <div class="colors-container">
      <h3 class="u-pull-left"><%= cs.name %></h3>
      <% if @user %>
        <% if @user == current_user %>
          <p class="u-pull-right"><span class="fa fa-trash-o" aria-hidden="true"></span> <%= link_to "Delete", user_color_scheme_path(user, cs), method: :delete %></p>
          <p class="u-pull-right"><span class="fa fa-pencil-square-o icon"></span><%= link_to "Edit", edit_user_color_scheme_path(user, cs) %></p>
        <% end %>
      <% end %>
      <p class="u-pull-right"><%= render partial: "favorites/favorite", locals: {color_scheme: cs} %></p>
      <div class="row">
        <div class="twelve columns">
          <% cs.colors.each do |c| %>
            <% if !c.color_scheme_colors.where(["color_id = ? and color_scheme_id = ?", c.id, cs.id]).first.color_note.blank? %>
              <div class="colors-index-20p-container tooltip">
                <%= content_tag(:div, nil, class: "colors-index-color", style:"background-color: #{c.hex_code};") %>
                <span class="fa fa-square-o color-note-indicator" aria-hidden="true"></span>
                <div class="colors-note-tooltiptext">
                  <%= c.color_scheme_colors.where(["color_id = ? and color_scheme_id = ?", c.id, cs.id]).first.color_note %>
                </div>
              </div>
            <% else %>
              <div class="colors-index-20p-container">
                <%= content_tag(:div, nil, class: "colors-index-color", style:"background-color: #{c.hex_code};") %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/color_schemes/_random.html.erb
<h1><%= random_scheme.name %></h1>

<div class="row">
  <div class="twelve columns">
    <% random_scheme.colors.each do |c| %>
      <% if !c.color_scheme_colors.where(["color_id = ? and color_scheme_id = ?", c.id, random_scheme.id]).first.color_note.blank? %>
        <div class="colors-index-20p-container tooltip">
          <%= content_tag(:div, nil, class: "colors-index-color", style:"background-color: #{c.hex_code};") %>
          <span class="fa fa-square-o color-note-indicator" aria-hidden="true"></span>
          <div class="colors-note-tooltiptext">
            <%= c.color_scheme_colors.where(["color_id = ? and color_scheme_id = ?", c.id, random_scheme.id]).first.color_note %>
          </div>
        </div>
      <% else %>
        <div class="colors-index-20p-container">
          <%= content_tag(:div, nil, class: "colors-index-color", style:"background-color: #{c.hex_code};") %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/color_schemes/_script.html.erb
<% content_for :script do %>
  <script>
    var target = document.querySelectorAll('input.width-20p-colors');

    // set hooks for each target element
    for (var i = 0, len = target.length; i < len; ++i) {
        (new CP(target[i])).on("change", function(color) {
            this.target.value = '#' + color;
            this.target.style.backgroundColor = '#' + color;
        });
    }
  </script>
<% end %>

app/views/color_schemes/edit.html.erb
<div class="container">

  <h1>Edit Color Scheme</h1>
  <%= render "form" %>

  <div class="row">
    <div class="twelve columns">
        <span class="fa fa-trash-o" aria-hidden="true"></span> <%= link_to "Delete Color Scheme", user_color_scheme_path(current_user, @color_scheme), method: :delete %>
    </div>
  </div>

</div>

<%= render "script" %>

app/views/color_schemes/index.html.erb
<div class="container">

  <% if @user && @user == current_user %>
    <h1>Your Color Schemes</h1>
    <%= render partial: "index", locals: {user: @user, color_schemes: @color_schemes} %>
  <% elsif @user && @user != current_user %>
    <h1> User <%= @user.id %>'s Color Schemes</h1>
    <%= render partial: "index", locals: {user: @user, color_schemes: @color_schemes} %>
  <% else %>
    <h1>All Color Schemes</h1>
    <%= render partial: "index", locals: {user: @user, color_schemes: @color_schemes} %>
  <% end %>

</div>

app/views/color_schemes/new.html.erb
<div class="container">

  <h1>New Color Scheme</h1>
  <%= render "form" %>

</div>

<%= render "script" %>

app/views/color_schemes/popular.html.erb
<div class="container">

<h1>Popular Color Schemes</h1>
  <% if @popular_color_schemes.empty? %>
    <p> No one has favorited any color schemes yet! </p>
  <% else %>
    <% @popular_color_schemes.each do |color_scheme| %>
      <div class="colors-container">
        <h3 class="u-pull-left"><%= color_scheme.name %></h3>
        <p class="u-pull-right">
          <%= render partial: "favorites/favorite", locals: {color_scheme: color_scheme} %>
        </p>
        <div class="row">
          <div class="twelve columns">
            <% color_scheme.colors.each do |c| %>
              <% if !c.color_scheme_colors.where(["color_id = ? and color_scheme_id = ?", c.id, color_scheme.id]).first.color_note.blank? %>
                <div class="colors-index-20p-container tooltip">
                  <%= content_tag(:div, nil, class: "colors-index-color", style:"background-color: #{c.hex_code};") %>
                  <span class="fa fa-square-o color-note-indicator" aria-hidden="true"></span>
                  <div class="colors-note-tooltiptext">
                    <%= c.color_scheme_colors.where(["color_id = ? and color_scheme_id = ?", c.id, color_scheme.id]).first.color_note %>
                  </div>
                </div>
              <% else %>
                <div class="colors-index-20p-container">
                  <%= content_tag(:div, nil, class: "colors-index-color", style:"background-color: #{c.hex_code};") %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>

</div>

app/views/color_schemes/random.html.erb
<div class="container">

      <%= render partial: "random", locals: { random_scheme: @random_scheme} %>

</div>

app/views/favorites/_favorite.html.erb
<% if current_user.favorites && current_user.favorites.include?(color_scheme) %>
  <span class="fa fa-star star-icon"></span><%= link_to "Unfavorite", user_favorite_path(current_user, color_scheme, type: "unfavorite"), method: :put %>
<% else %>
  <span class="fa fa-star-o star-icon"></span><%= link_to "Favorite", user_favorite_path(current_user, color_scheme, type: "favorite"), method: :put %>
<% end %>

app/views/favorites/index.html.erb
<div class="container">

  <% if @user == current_user %>
    <h1>Your Favorites</h1>
  <% elsif @user != current_user %>
    <h1>User <%= @user.id %>'s Favorites</h1>
  <% end %>

  <% if @favorites.empty? %>
    <p> No favorites yet! </p>
  <% else %>
    <% @favorites.each do |fav| %>
      <div class="colors-container">
        <h3 class="u-pull-left"><%= fav.name %></h3>

        <p class="u-pull-right">
          <%= render partial: "favorite", locals: {color_scheme: fav} %>
        </p>
        <div class="row">
          <div class="twelve columns">
            <% fav.colors.each do |c| %>
              <% if !c.color_scheme_colors.where(["color_id = ? and color_scheme_id = ?", c.id, fav.id]).first.color_note.blank? %>
                <div class="colors-index-20p-container tooltip">
                  <%= content_tag(:div, nil, class: "colors-index-color", style:"background-color: #{c.hex_code};") %>
                  <span class="fa fa-square-o color-note-indicator" aria-hidden="true"></span>
                  <div class="colors-note-tooltiptext">
                    <%= c.color_scheme_colors.where(["color_id = ? and color_scheme_id = ?", c.id, fav.id]).first.color_note %>
                  </div>
                </div>
              <% else %>
                <div class="colors-index-20p-container">
                  <%= content_tag(:div, nil, class: "colors-index-color", style:"background-color: #{c.hex_code};") %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Schemer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400" rel="stylesheet">
  </head>

  <body>

    <div id="header">

      <div id="current-user-data" data-current-user-id="<%= current_user.id %>"></div>

      <% if current_user %>
        <nav>
          <span class="u-pull-left">
            <%= image_tag "schemerlogo.png", height: "30px", class: "logo" %>
            <span class="fa fa-home" aria-hidden="true"></span><%= link_to "Home", root_path, class: "navspace"%>
            <span class="fa fa-th" aria-hidden="true"></span><%= link_to "All", color_schemes_path, class: "navspace" %>
            <span class="fa fa-fire" aria-hidden="true"></span><%= link_to "Popular", popular_path, class: "navspace" %>
            <span class="fa fa-question" aria-hidden="true"></span><%= link_to "Random", random_path, class: "navspace", id: "randomlink" %>
            <span class="fa fa-star" aria-hidden="true"></span><%= link_to "Your Favorites", user_favorites_path(current_user), class: "navspace" %>
            <span class="fa fa-th-large" aria-hidden="true"></span><%= link_to "Your Schemes", user_color_schemes_path(current_user), class: "navspace", id: "yourschemeslink" %>
            <span class="fa fa-plus" aria-hidden="true"></span><%= link_to "Create Color Scheme", new_user_color_scheme_path(current_user), class: "navspace" %>
          </span>
          <span class="u-pull-right">
            <span class="fa fa-sign-out" aria-hidden="true"></span><%= link_to "Log Out", logout_path(@current_user), method: :delete, class: "navspace" %>
            <span class="navspace"><%= current_user.email %></span>
          </span>
        <nav>
      <% end %>

      <div class="alertcontainer">
        <% if flash[:error] || flash[:success] %>
          <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>"><%= value %></div>
          <% end %>
        <% end %>
      </div>

      <br>
      <br>

    </div>

    <div id="content">

      <%= yield %>

      <%= yield :script %>

    </div>

    <script id="color-scheme-template" type="text/x-handlebars-template">
      <div class="container">
        <button id="filter" class="u-pull-right">Filter</button>
        <br>
        <br>
        {{#if user.color_schemes}}
          {{#each user.color_schemes}}
            <div class="colors-container">
              <h3 class="u-pull-left">{{name}}</h3>
                <p class="u-pull-right"><span class="fa fa-trash-o" aria-hidden="true"></span> <a data-method="delete" href="/users/{{user_id}}/color_schemes/{{id}}">Delete</a></p>
                <p class="u-pull-right"><span class="fa fa-pencil-square-o icon"></span><a href="/users/{{user_id}}/color_schemes/{{id}}/edit">Edit</a></p>
                <p class="u-pull-right">
                {{#if favorite}}
                  <span class="fa fa-star star-icon"></span><a data-method="put" href="/users/{{../currentUserId}}/favorites/{{id}}?type=unfavorite">Unfavorite</a>
                {{else}}
                  <span class="fa fa-star-o star-icon"></span><a data-method="put" href="/users/{{../currentUserId}}/favorites/{{id}}?type=favorite">Favorite</a>
                {{/if}}
                </p>
                <div class="row">
                  <div class="twelve columns">
                    {{#each colors}}
                          {{#if color_note}}
                            <div class="colors-index-20p-container tooltip">
                              <div class="colors-index-color" style="background-color: {{hex_code}}"></div>
                              <span class="fa fa-square-o color-note-indicator" aria-hidden="true"></span>
                              <div class="colors-note-tooltiptext">
                                {{color_note}}
                              </div>
                            </div>
                          {{else}}
                            <div class="colors-index-20p-container">
                              <div class="colors-index-color" style="background-color: {{hex_code}}"></div>
                            </div>
                          {{/if}}
                    {{/each}}
                </div>
              </div>
            </div>
          {{else}}
            <p> No color schemes yet! </p>
            <span class="fa fa-plus" aria-hidden="true"></span> <a href="/users/{{currentUserId}}/color_schemes/new">Create One!</a>
          {{/each}}
        {{/if}}
      </div>
    </script>

  </body>
</html>

app/views/users/_home.html.erb
  <div class="colors-container">
    <h4 class="u-pull-left"><%= var.name %></h4>
    <div class="row">
      <div class="twelve columns">
        <% var.colors.each do |c| %>
          <%= content_tag(:div, nil, class: "colors-index-20p", style:"background-color: #{c.hex_code};") %>
        <% end %>
      </div>
    </div>
  </div>

app/views/users/dashboard.html.erb
<div class="container">

  <div class="row">

    <div class="six columns">
      <h2>Your Color Schemes</h2>
        <% current_user.color_schemes.each do |cs| %>
          <div class="colors-container">
            <h4 class="u-pull-left"><%= cs.name %></h4>
            <div class="row">
              <div class="twelve columns">
                <% cs.colors.each do |c| %>
                  <%= content_tag(:div, nil, class: "colors-index-20p", style:"background-color: #{c.hex_code};") %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
    </div>

    <div class="six columns">
      <h2>Favorite Color Schemes</h2>
        <% current_user.favorite_color_schemes.each do |fcs| %>
          <div class="colors-container">
            <h4 class="u-pull-left"><%= fcs.name %></h4>
            <div class="row">
              <div class="twelve columns">
                <% fcs.colors.each do |c| %>
                  <%= content_tag(:div, nil, class: "colors-index-20p", style:"background-color: #{c.hex_code};") %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
    </div>

  </div>

</div>

app/views/users/home.html.erb
<div class="container">

  <div class="row">

    <div class="six columns">
      <h2>Your Color Schemes</h2>
        <% if current_user.color_schemes.empty? %>
          <p>You haven't created any color schemes yet!</p>
          <span class="fa fa-plus" aria-hidden="true"></span> <%= link_to "Create one!", new_user_color_scheme_path(current_user) %>
        <% else %>
          <% current_user.color_schemes.each do |cs| %>
            <%= render partial: "home", locals: {var: cs, cs: cs} %>
          <% end %>
        <% end %>
    </div>

    <div class="six columns">
      <h2>Your Favorites</h2>
        <% if current_user.favorites.empty? %>
          <p>You haven't favorited any color schemes yet!</p>
        <% else %>
          <% current_user.favorites.each do |fav| %>
            <%= render partial: "home", locals: {var: fav, cs: fav} %>
          <% end %>
        <% end %>
    </div>

  </div>

</div>

app/views/users/new.html.erb
<div class="logintopcontainer">
  <%= image_tag "schemerlogo.png", height: "75px"%>
  <h1 class="text-center">Signup</h1>
</div>

<%= form_for :user do |f| %>
<div class="logincontainer">

  <% if flash[:loginerror] %>
    <div class="alert-loginerror"><%= flash[:loginerror] %></div>
  <% end %>
  
  Email <br>
  <%= f.text_field :email %> <br>
  Password <br>
  <%= f.password_field :password %> <br>
  Confirm Password <br>
  <%= f.password_field :password_confirmation %> <br>
  <br>
  <%= f.submit "Sign Up", class: "button-primary" %>
</div>
<p class="text-center sm"><%= link_to "Already have an account? Log in", login_path %></h1>
<% end %>